### ISSUE TITLE
Unhandled Exception with all HW2 files.

### ISSUE THREAD

**Issue by thomcomstock** [Fallen-Angel/CFHodEd#7]
I have been able to open every file attempted with CFHodEd v.4.1.00 yet any attempt to open any HOD file with this (CFHodEd v.4.1.1.0 results in the following error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Homeworld2.HOD.Texture.Mip.ReadIFF(IFFReader IFF, String FourCC)
   at Homeworld2.HOD.Texture.ReadIFF(IFFReader IFF, ChunkAttributes ChunkAttributes)
   at Homeworld2.HOD.HOD.ReadLMIPChunk(IFFReader IFF, ChunkAttributes ChunkAttributes)
   at Homeworld2.IFF.Chunk.Read()
   at Homeworld2.IFF.IFFReader.Parse(Boolean FromBegining)
   at Homeworld2.HOD.HOD.ReadHVMDChunk(IFFReader IFF, ChunkAttributes ChunkAttributes)
   at Homeworld2.IFF.Chunk.Read()
   at Homeworld2.IFF.IFFReader.Parse(Boolean FromBegining)
   at Homeworld2.HOD.HOD.Read(Stream stream)
   at CFHodEd.HODEditorA._OpenHOD()
   at CFHodEd.HODEditorA.mnuFileOpen_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   
   thomcomstock at yah oo dot etc.
   
   Thank you for your time and hard work.

**Comment by thomcomstock** [comment]
That having been said, I have found that this version will open some of the HWR hod files that the previous version balked at, and once I have saved them, they can be opened by the previous version, but even left just as saved by this version, they are then unaccessable to this version. In other words: Files saved by this version can no longer be opened by this version, but generate an unhandled exception.

I would really like some feedback concerning this issue.

**Comment by Mephistofeles** [comment]
I'm assuming you're using RM 2.0 files. Have you tried using [version 4.2.0.0](https://github.com/Fallen-Angel/CFHodEd/releases/tag/v4.2.0.0)?

**Comment by thomcomstock** [comment]
Pawel,

Thank you so very much for responding to my inquiry. Actually, I am modding HW2, not RM. However, I am always up to having an array of tools at my disposal.

Thom Comstock

"None are so hopelessly enslaved as those who falsely believe they are free."
~ Johann Wolfgang von Goethe    

    On Monday, September 27, 2021, 04:00:46 AM EDT, Paweł Słowik ***@***.***> wrote:  
 
 


I'm assuming you're using RM 2.0 files. Have you tried using version 4.2.0.0?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mephistofeles** [comment]
Oh, sorry, now I see HW2 in the title. I have not tested the new versions with HW2 hods,   I was focused only on RM compatibility.

**Comment by thomcomstock** [comment]
I have briefly tried the RM 2.0 in order to open HWRM hods and then (hopefully, perhaps) save the hods in a usable form for HW2, but I have as yet not found one HWRM hodfile that will open in RM 2.0.

Thom Comstock

"None are so hopelessly enslaved as those who falsely believe they are free."
~ Johann Wolfgang von Goethe    

    On Tuesday, September 28, 2021, 05:52:49 PM EDT, Paweł Słowik ***@***.***> wrote:  
 
 


Oh, sorry, now I see HW2 in the title. I have not tested the new versions with HW2 hods, I was focused only on RM compatibility.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
